name: .NET Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore test project dependencies
        run: dotnet restore tests/WNAB.Tests.Unit/WNAB.Tests.Unit.csproj

      - name: Build test project
        run: dotnet build tests/WNAB.Tests.Unit/WNAB.Tests.Unit.csproj --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test tests/WNAB.Tests.Unit/WNAB.Tests.Unit.csproj --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
