name: .NET Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Run unit tests
        run: dotnet test tests/WNAB.Tests.Unit/WNAB.Tests.Unit.csproj --configuration Release --logger "trx;LogFileName=test_results.trx"
